name: steel_suvidha
description: A new Flutter project for Steel Suvidha.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_animate: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/tmt.png
    - assets/images/angle.png
    - assets/images/flats.png
    - assets/images/square_bar.png
    - assets/images/round_bar.png
    - assets/images/channel.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
